# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20170820_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planocontasgrupo',
            options={'permissions': (('view_planocontasgrupo', 'Can view plano contas'),), 'verbose_name': '帐户组'},
        ),
    ]
