# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20170820_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.NaturezaOperacao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupo_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.GrupoFiscal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Unidade'),
        ),
    ]
