# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20180712_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': (('view_produto', 'Can view produto'),), 'verbose_name': '产品'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'permissions': (('view_unidade', 'Can view unidade'),), 'verbose_name': '单位'},
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo_endereco',
            field=models.CharField(blank=True, choices=[('UNI', '唯一的'), ('RES', 'Residencial'), ('COM', 'Comercial'), ('COB', 'Cobrança'), ('ENT', 'Entrega'), ('OUT', 'Outro')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='sit_fiscal',
            field=models.CharField(blank=True, choices=[('LR', '实际利润'), ('LP', '假设利润'), ('SN', '简单的国家'), ('SE', '简单的国家过度的高收入')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo_telefone',
            field=models.CharField(blank=True, choices=[('FIX', ''), ('CEL', '固话'), ('FAX', '传真'), ('OUT', '手机')], max_length=8, null=True),
        ),
    ]
