# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20180712_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='tipo_movimento',
            field=models.CharField(choices=[('0', 'Ajuste'), ('1', 'Entrada por pedido de compra'), ('2', '从供应商导入的收据'), ('3', 'Ajuste inicial')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='tipo_movimento',
            field=models.CharField(choices=[('0', '结算'), ('1', '出口订单'), ('2', '出口退税')], default='0', max_length=1),
        ),
    ]
